In [2]:
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# load data

In [3]:
train_data = pd.read_csv("./train_nov28_task1.csv")
test_data = pd.read_csv("./test_nov28_task1_only_features.csv")

In [4]:
train_data.head()

feature0  feature1   feature2   feature3   feature4 class
0  4.115910  8.678126  16.010297   5.731837  18.907271     A
1  1.993343  8.920002  15.332958  10.389251   0.023662     A
2  0.095994  8.847990   7.292827   4.059212   7.914817     A
3  3.808525  8.726179  13.842177   9.997444   0.178466     A
4  4.554317  8.850917  15.659514   8.053744   0.341788     A

In [5]:
X = train_data.iloc[:,1:5]
y = train_data.iloc[:,5:]

In [6]:
y.tail()

class
3595     C
3596     C
3597     C
3598     C
3599     C

In [7]:
test_data.tail()

feature0  feature1   feature2   feature3   feature4
595  1.680964  8.997714  13.848865  18.064389  17.986049
596  5.698785  8.998488   9.970493  19.993208  19.885641
597  3.244223  8.998757   7.576489  13.780486  24.439806
598  1.588390  8.999924  14.920500  18.602443  14.978804
599  4.820494  8.999993   9.180042  16.018661   4.614099

In [8]:
test_data.iloc[0:603,0:5].head()

feature0  feature1   feature2   feature3   feature4
0  1.090442  8.108149  10.863764  20.673382   0.258073
1  1.913153  8.115473  12.656546  14.695447  17.861850
2  5.747883  8.117581   9.322548  15.385807   1.281899
3  0.605095  8.117733  15.676220  27.224439  13.524959
4  4.975120  8.122020   7.791070  28.519339  14.480148

In [9]:
#IQR0 = X.iloc[:,0:1].quantile(0.75) - X.iloc[:,0:1].quantile(0.25)
#IQR1 = X.feature1.quantile(0.75) - X.feature1.quantile(0.25)
#IQR2 = X.feature2.quantile(0.75) - X.feature2.quantile(0.25)
#IQR3 = X.feature3.quantile(0.75) - X.feature3.quantile(0.25)
#IQR4 = X.feature4.quantile(0.75) - X.feature4.quantile(0.25)

# split data for training and validation

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

# Support Vector Machine

In [15]:
from sklearn.svm import SVC
#from sklearn.model_selection import GridSearchCV
#param_grid = {'C':[0.01,0.1,1],'kernel':['rbf','poly','linear','sigmoid'],'gamma':[0.01,0.1,1]}
#grid = GridSearchCV(svm,param_grid)
#grid.fit(X,y)
#print("grid.best_params_ = ",grid.best_params_,", grid.best_score_ =" ,grid.best_score_)

svm = SVC()
svm = SVC(kernel = "rbf",C =5, gamma = 1.123)
#svm = SVC(kernel = "poly", C = 1.005, degree = 5, gamma = 0.0132, max_iter = 20000000)
#svm = SVC(kernel = "linear", degree = 5)
svm.fit(X_train,y_train)

/Users/jonner/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(C=5, gamma=1.123)

In [16]:
svm.score(X_val,y_val)

0.946969696969697

# put validation data back for training a better model

In [17]:
svm.fit(X,y)

/Users/jonner/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(C=5, gamma=1.123)

In [16]:
svm.predict

<bound method BaseSVC.predict of SVC(C=5.05, gamma=1.2)>

In [55]:
#from sklearn.neighbors import KNeighborsClassifier
#knn = KNeighborsClassifier(n_neighbors = 1)
#knn.fit(X_train,y_train)

/Users/jonner/opt/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=1)

In [56]:
#knn.score(X_val,y_val)

0.9444444444444444

In [53]:
#from sklearn import cluster
#kmeans_fit = cluster.KMeans(n_clusters = 3, max_iter = 3000, n_init = 100).fit(X_train)

In [54]:
#kmeans_fit.labels_

array([0, 1, 1, ..., 0, 2, 2], dtype=int32)

# Write the result into csv file

In [17]:
id = np.linspace(1,600,600,dtype = "int")


In [18]:
id

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [19]:
arr = svm.predict(test_data.iloc[:,1:5])

In [20]:
a = np.concatenate((id,arr))

In [21]:
a = a.reshape(2,600)

In [22]:
a = np.transpose(a, axes=None)

In [26]:
pd.DataFrame(a).tail()

0  1
595  596  C
596  597  B
597  598  C
598  599  A
599  600  A

雖然有寫到csv 但還是要進去檔案裡把第一個column刪掉才行XD

In [25]:
df = pd.DataFrame(a, columns = ['Id','Category'])
df.to_csv('answer.csv', columns=['Id','Category'])

# 其他的東東

In [67]:
from sklearn.linear_model import LogisticRegression
start = time.time()
clf = LogisticRegression(solver = "newton-cg")
clf.fit(X,y)
print(time.time()-start)

0.20003795623779297


/Users/jonner/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [68]:
clf.predict(X)

array(['A', 'A', 'A', ..., 'C', 'A', 'C'], dtype=object)

In [69]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, clf.predict(X))

array([[974, 108, 118],
       [124, 874, 202],
       [143, 187, 870]])

In [76]:
score = clf.score(X_val, y_val)

In [77]:
score

0.7592592592592593